services:
  main-db:
    image: postgres:15-alpine
    container_name: library-db-postgress
    environment:
      - POSTGRES_DB=library
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
    ports:
      - 5432
  main-server:
    build: .
    image: main-service_image
    container_name: main-service
    depends_on:
      - main-db
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://main-db:5432/library
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root