services:
  library-db:
    image: postgres:15-alpine
    container_name: library-db-postgress
    environment:
      - POSTGRES_DB=library
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
    ports:
      - 5432
  library-server:
    build: .
    image: library-service_image
    container_name: library-service
    depends_on:
      - library-db
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://library-db:5432/library
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root