CREATE TABLE IF NOT EXISTS author
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_author PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS book
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name      VARCHAR(255)                            NOT NULL,
    isbn      BIGINT                                  NOT NULL,
    author_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_book PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS author
    ADD CONSTRAINT uc_author_name UNIQUE (name);

ALTER TABLE IF EXISTS book
    ADD CONSTRAINT uc_book_isbn UNIQUE (isbn);

ALTER TABLE IF EXISTS book
    ADD CONSTRAINT FK_BOOK_ON_AUTHOR FOREIGN KEY (author_id) REFERENCES author (id);